### ISSUE TITLE
LICENSE file 

### ISSUE THREAD

**Issue by peekxc** [shaelebrown/TDAML#1]
Hyy @shaelebrown, 

Could you add plain-text LICENSE or COPYING file to the repo, or are you fine explicitly leaving one out? 

JOSS requires such a file, and for repos hosted on GH it's nice to have, as the license is detected and shown immediately in a 'tab' next to the README.  

CRAN standards allow omitting a License file if its generic enough, but you can also point to the LICENSE file directly via 'file LICENSE' (see https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Licensing-1)

See also [#6321](https://github.com/openjournals/joss-reviews/issues/6321#issuecomment-1938909073)

**Comment by shaelebrown** [comment]
Hey @peekxc 

I didn't originally have a license file but I did add one at the start of the review process: https://github.com/shaelebrown/TDApplied/blob/JOSS/LICENSE.md

Let me know if that's alright!

**Comment by peekxc** [comment]
Ahh I see it's on a separate branch. Thanks!
