### ISSUE TITLE
How to contribute? 

### ISSUE THREAD

**Issue by peekxc** [shaelebrown/TDAML#2]
@shaelebrown Could you add a note to the README.md about how to contribute, or consider adding a [contributing.md](https://mozillascience.github.io/working-open-workshop/contributing/)? I apologize if this is shown elsewhere

[#6321](https://github.com/openjournals/joss-reviews/issues/6321)

**Comment by shaelebrown** [comment]
Great point @peekxc. Do you know if I update the main branch or the JOSS branch?

**Comment by peekxc** [comment]
whichever one you want, I assume whichever is the most up to date

**Comment by shaelebrown** [comment]
The JOSS branch is the most up to date for this review, but I'm not sure if whatever changes I make should be on the main branch for a future CRAN update or not

**Comment by peekxc** [comment]
Isn't the goal to eventually merge the JOSS branch into main? 

I don't think it matters which one you modify. Once they merge, it'll make no difference

( I might be misunderstanding something here )

**Comment by shaelebrown** [comment]
I think you're right. I've updated the README.Rmd and README.md files with notes on how to contribute. I'll close the issue for now but let me know if I should add in anything else!
