### ISSUE TITLE
Documentation outline

### ISSUE THREAD

**Issue by peekxc** [shaelebrown/TDAML#3]
While each of the individual functions in TDApplied are well documented (e.g. analyze_representatives, plot_diagrams, etc.), it would be nice to have an outline view of all the functions somewhere, e.g. in the package overview ("TDApplied::`TDApplied-package`").

Similarly, while there _are_ links to other package functions in the descriptions of the arguments and details, I think the designated ways of doing this that are a bit more common (see: https://cran.r-project.org/web/packages/roxygen2/vignettes/index-crossref.html)

[#6321](https://github.com/openjournals/joss-reviews/issues/6321)

**Comment by shaelebrown** [comment]
That's a great comment, thanks. Can you send me an example from another package? I've never seen that before.

In terms of the cross references I followed the conventions in this link https://cran.r-project.org/doc/manuals/R-exts.html#Cross_002dreferences to make xrefs. When I tried to follow the instructions in your link you sent, updating the analyze_representatives.R file, running `devtools::document()` and check the `help("analyze_representatives")` help page it doesn't seem to format properly (see screen grab):
 
<img width="387" alt="Screen Shot 2024-03-04 at 11 57 39 AM" src="https://github.com/shaelebrown/TDApplied/assets/56615362/01c04c7e-efb1-4547-b08f-fb116ffd7678">

What do you suggest?

**Comment by peekxc** [comment]
> Can you send me an example from another package? I've never seen that before.

Sure, you can try ?ggplot2::`ggplot2-package` to get an idea of simple one. To see how to set it up, see e.g. [here](https://r-pkgs.org/man.html#sec-man-package-doc). 

A more informal example that doesn't generate an entire package-specific page is `?dplyr::select`'s page. There's not only a nice overview of the functions it composes with (contains(), matches(), etc.), but also a nice "see also" section linking to other single-verb functions that behave similarly (arrange(), mutate(), filter(), etc.). 'See also' links are mentioned in the same CRAN xref page you linked. 

Similar functionality in TDApplied might benefit from such "see also" linking; `diagram_mds`, `diagram_kpca` are both projections of diagrams, `permutation_test` and `independence_test` are both types of hypothesis tests for diagrams, etc.

> When I tried to follow the instructions in your link you sent, updating the analyze_representatives.R file, running devtools::document() and check the help("analyze_representatives") help page it doesn't seem to format properly (see screen grab):

I guess the exact syntax may differ based on the roxygen version or something, whatever way of making cross references works for you!

**Comment by shaelebrown** [comment]
Awesome. Added in the `TDApplied-package` function, and added `seealso` linking in function documentation. The cross refs are working for me so I left them unchanged. Let me know if all looks good and I'll close the issue!

**Comment by peekxc** [comment]
Thanks! I think its def a bit easier to navigate now :)
