### ISSUE TITLE
Online docs / vignettes

### ISSUE THREAD

**Issue by peekxc** [shaelebrown/TDAML#4]
While `TDApplied`'s docs and vignettes are nice and self-contained (appropriate for local download + use), I think the vignettes would look beautiful if posted online. 

Have you considered building e.g. a [pkgdown](https://pkgdown.r-lib.org/) site @shaelebrown ?

**Comment by shaelebrown** [comment]
Thank you, that's a great suggestion @peekxc. I was actually wondering how to do that (having seen other packages with websites but not knowing how they did it). I'll look into it (outside of this review process) and close this issue.
